import type { Metadata } from "next";
import { BRAND, SITE_URL } from "@/data/site";

/** Committed 1200x630 social preview, generated by scripts/generate-og.mjs. */
export const SOCIAL_IMAGE = {
  url: "/brand/og.png",
  width: 1200,
  height: 630,
  alt: `${BRAND} — The first NPC that lives in your world.`,
} as const;

interface PageSeo {
  title: string;
  description: string;
  /** Route path with a leading and trailing slash, e.g. "/npc-world/". */
  path: string;
}

/**
 * Consistent per-route metadata: canonical URL plus matching Open Graph and
 * Twitter cards. Pages must pass the social image explicitly because a
 * page-level `openGraph` object replaces the layout's default.
 */
export function pageMetadata({ title, description, path }: PageSeo): Metadata {
  const url = `${SITE_URL}${path}`;
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      url,
      siteName: BRAND,
      title,
      description,
      images: [SOCIAL_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [SOCIAL_IMAGE.url],
    },
  };
}
