import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { WORLD_SCENARIOS } from "../src/data/npcWorldPage.ts";
import { threadDuration } from "../src/domain/world/playback.ts";
const duration = threadDuration(WORLD_SCENARIOS[0].posts.length);
const { chromium } = await import(process.env.REALNPC_PLAYWRIGHT_MODULE ?? "playwright");
const base = process.env.REALNPC_BASE_URL ?? "http://127.0.0.1:4173";
assert.ok(["localhost", "127.0.0.1", "[::1]"].includes(new URL(base).hostname));
const browser = await chromium.launch({ channel: process.env.REALNPC_BROWSER_CHANNEL || undefined, headless: true });
const artifacts = process.env.REALNPC_WORLD_ARTIFACTS ?? "/tmp/realnpc-world-threads";
await mkdir(artifacts, { recursive: true });
const errors = [];
try {
  for (const width of [320, 390, 768, 1440]) {
    const page = await browser.newPage({ viewport: { width, height: 1000 }, reducedMotion: "reduce", deviceScaleFactor: width === 1440 ? 2 : 1 });
    page.on("pageerror", error => errors.push(error.message));
    await page.goto(`${base}/npc-world/`, { waitUntil: "networkidle" });
    const preview = page.getByRole("region", { name: "NPC World product concept", exact: true });
    const list = page.getByRole("group", { name: "Choose a conversation", exact: true });
    assert.equal(await page.locator(".npc-globe-hero aside").count(), 0);
    assert.equal(await preview.getByRole("group", { name: "Choose a World conversation", exact: true }).count(), 1);
    const copyBox = await page.locator(".npc-hero-copy").boundingBox();
    const globeBox = await page.locator(".npc-globe-canvas").boundingBox();
    if (width >= 1024) assert.ok(copyBox.x + copyBox.width <= globeBox.x, "Hero copy must not cover the globe");
    else assert.ok(copyBox.y + copyBox.height <= globeBox.y, "Mobile hero stacks without overlap");
    await page.locator(".npc-globe-canvas canvas").waitFor();
    await page.screenshot({ path: `${artifacts}/hero-${width}.png` });
    for (const id of ["business", "community", "leisure"]) {
      const choice = preview.locator(`.npc-scenario-choice[data-scenario="${id}"]`);
      await choice.focus(); await page.keyboard.press("Space");
      assert.equal(await choice.getAttribute("aria-pressed"), "true");
      assert.equal(await list.locator(`[data-scenario="${id}"]`).getAttribute("aria-pressed"), "true");
    }

    assert.equal(await list.getByRole("button").count(), 9);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await preview.screenshot({ path: `${artifacts}/threads-${width}.png`, style: "header { visibility: hidden !important; }" });
    assert.equal(await page.getByRole("button", { name: "Replay activity" }).count(), 0);
    assert.equal(await page.locator(".npc-thread-post").count(), 7);

    await page.getByRole("button", { name: "Save", exact: true }).click();
    await page.getByRole("button", { name: "Saved (1)", exact: true }).click();
    assert.equal(await list.getByRole("button").count(), 1);
    await page.getByRole("button", { name: "Saved", exact: true }).click();
    assert.equal(await list.getByRole("button").count(), 0);
    assert.ok(await page.getByText("No saved threads yet.", { exact: false }).isVisible());
    await page.getByRole("button", { name: "All", exact: true }).click();
    const search = page.getByRole("searchbox", { name: "Search discussions" });
    await search.fill(WORLD_SCENARIOS.find(scenario => scenario.id === "community").topic);
    assert.equal(await list.getByRole("button").count(), 1);
    await search.fill("no-such-thread");
    assert.equal(await list.getByRole("button").count(), 0);
    await search.fill("");
    await page.getByLabel("Sort discussions").selectOption("top");
    assert.equal(await list.getByRole("button").first().getAttribute("data-scenario"), "community");

    for (const { id, posts, topic, takeaway } of [...WORLD_SCENARIOS.slice(1), WORLD_SCENARIOS[0]]) {
      const button = list.locator(`[data-scenario="${id}"]`);
      await button.focus(); await page.keyboard.press("Enter");
      assert.equal(await button.getAttribute("aria-pressed"), "true");
      if (width < 768) assert.ok(await page.locator(".npc-thread-title h3").evaluate(node => node === document.activeElement));
      else assert.ok(await button.evaluate(node => node === document.activeElement));
      assert.equal(await page.locator(".npc-thread-post").count(), posts.length);
      const people = new Set(posts.map(post => post.actor.handle)).size;
      assert.equal(await button.locator(".npc-feed-avatar").count(), people);
      assert.ok((await page.locator(".npc-thread-byline").textContent()).includes(`${people} NPCs in this conversation`));
      assert.equal(await page.locator(".npc-thread-title h3").textContent(), topic);
      await page.getByRole("button", { name: "Back with you", exact: true }).click();
      assert.equal(await page.locator(".npc-home-message blockquote").textContent(), takeaway);
      await page.getByRole("button", { name: "Thread", exact: true }).click();
    }
    const upvote = page.getByRole("button", { name: "Upvote this thread" });
    const votes = Number(await upvote.textContent());
    await upvote.focus(); await page.keyboard.press("Space");
    assert.equal(Number(await upvote.textContent()), votes + 1);
    await page.keyboard.press("Space");
    assert.equal(Number(await upvote.textContent()), votes);
    const collapse = page.getByRole("button", { name: "Collapse replies to Mia" }).first();
    await collapse.focus(); await page.keyboard.press("Enter");
    assert.equal(await page.locator(".npc-reply-branch").first().isVisible(), false);
    assert.ok(await page.getByRole("button", { name: "Expand replies to Mia" }).first().evaluate(node => node === document.activeElement));
    await page.keyboard.press("Space");
    assert.equal(await page.locator(".npc-reply-branch").first().isVisible(), true);
    await page.getByRole("button", { name: "Back with you", exact: true }).focus();
    await page.keyboard.press("Enter");
    assert.ok(await page.locator(".npc-home-message").isVisible());
    await page.keyboard.press("Shift+Tab");
    assert.equal(await page.evaluate(() => document.activeElement.textContent), "Thread");
    await page.keyboard.press("Enter"); await page.keyboard.press("Tab"); await page.keyboard.press("Escape");
    assert.ok(await page.getByRole("button", { name: "Back with you", exact: true }).evaluate(node => node === document.activeElement));
    const value = page.getByRole("region", { name: "A wider world. A richer companion." });
    assert.equal(await page.getByText("THREE WAYS TO MEET THE WORLD").count(), 0);
    assert.equal(await page.locator(".npc-value-reasons article").count(), 3);
    await value.screenshot({ path: `${artifacts}/value-${width}.png`, style: "header { visibility: hidden !important; }" });
    await page.close();
    console.log(`PASS ${width}px discussions: search, sorting, votes, saved filter, nested replies, keyboard, reduced motion`);
  }

  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
  page.on("pageerror", error => errors.push(error.message));
  await page.goto(`${base}/npc-world/`, { waitUntil: "networkidle" });
  await page.getByRole("button", { name: "Replay activity", exact: true }).click();
  const stage = page.locator(".npc-thread-conversation");
  await page.waitForFunction(() => Number(document.querySelector(".npc-thread-conversation").dataset.elapsed) > 3800);
  assert.equal(await page.locator(".npc-typing-caret").count(), 2, "Two NPCs compose concurrently");
  await page.getByRole("button", { name: "Pause", exact: true }).click();
  const paused = await stage.getAttribute("data-elapsed");
  await page.waitForTimeout(350);
  assert.equal(await stage.getAttribute("data-elapsed"), paused);
  await page.getByRole("button", { name: "Resume", exact: true }).click();
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: "instant" }));
  await page.waitForTimeout(250);
  const offscreen = await stage.getAttribute("data-elapsed");
  await page.waitForTimeout(350);
  assert.equal(await stage.getAttribute("data-elapsed"), offscreen, "Offscreen replay pauses");
  await page.getByRole("button", { name: "Pause", exact: true }).scrollIntoViewIfNeeded();
  await page.waitForTimeout(250);
  await page.evaluate(() => { Object.defineProperty(document, "visibilityState", { configurable: true, value: "hidden" }); document.dispatchEvent(new Event("visibilitychange")); });
  await page.waitForTimeout(150);
  const background = await stage.getAttribute("data-elapsed");
  await page.waitForTimeout(350);
  assert.equal(await stage.getAttribute("data-elapsed"), background, "Hidden-document event pauses replay");
  await page.evaluate(() => { delete document.visibilityState; document.dispatchEvent(new Event("visibilitychange")); });
  const timeline = page.getByRole("slider", { name: "Conversation playback position" });
  await timeline.focus(); await page.keyboard.press("End");
  assert.equal(await stage.getAttribute("data-elapsed"), String(duration));
  assert.equal(await page.locator(".npc-thread-post").count(), 7);
  assert.match(await page.locator(".npc-note-revision").textContent(), /revision 2/);
  await page.keyboard.press("Home");
  assert.equal(await stage.getAttribute("data-elapsed"), "0");
  assert.equal(await page.locator(".npc-thread-post").count(), 1);
  assert.match(await page.locator(".npc-note-revision").textContent(), /revision 1/);
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.waitForFunction(end => document.querySelector(".npc-thread-conversation").dataset.elapsed === String(end), duration);
  assert.equal(await stage.getAttribute("data-elapsed"), String(duration));
  assert.equal(await page.locator(".npc-thread-post").count(), 7);
  await page.close();
  assert.deepEqual(errors, []);
  console.log("PASS replay: concurrent typing, pause/resume, offscreen/background suspension, timeline scrubbing, reduced-motion changes; no page errors");
} finally { await browser.close(); }
