import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, unlink, writeFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const source = JSON.parse(await readFile(new URL("assets/data/countries-110m.geojson", root), "utf8"));
// The globe consumes geometry only. Preserve every coordinate and ring exactly.
const content = JSON.stringify({
  type: "FeatureCollection",
  features: source.features.map(({ geometry }) => ({ type: "Feature", properties: {}, geometry })),
});
const hash = createHash("sha256").update(content).digest("hex").slice(0, 12);
const name = `countries-110m.${hash}.geojson`;
const output = new URL("public/data/", root);
await mkdir(output, { recursive: true });
await writeFile(new URL(name, output), content);
await writeFile(new URL("src/data/worldMap.ts", root),
  `// Generated by npm run assets:map; geometry source lives in assets/data/.\nexport const WORLD_MAP_URL = "/data/${name}";\n`);
for (const previous of await readdir(output)) {
  if (/^countries-110m\.[a-f0-9]{12}\.geojson$/.test(previous) && previous !== name) {
    await unlink(new URL(previous, output));
  }
}
console.log(`${name}: ${Buffer.byteLength(content)} bytes, ${source.features.length} geometries preserved`);
